### ISSUE TITLE
server crashed cause by latch

### ISSUE THREAD

**Issue by bunSakurAing** [IchorDev/Latch#24]
https://pastebin.com/TgvmEW3Q
i can't start my server

**Comment by parlough** [comment]
Thanks for the report. It seems to be that the Metrics class is not there, which is strange since it should be and works fine for me locally. I have some some small changes prepared, not ready, but they may fix your issue though so I may try those out and release a small patch update if I feel it may solve the problem.

**Comment by parlough** [comment]
I think this should be fixed in the [0.4.2](https://ore.spongepowered.org/IchorPowered/Latch/versions/0.4.2) release. I'll be closing this, but feel free to reopen it if there are anymore problems. Thanks for the report!
