### ISSUE TITLE
open chest locked for admin

### ISSUE THREAD

**Issue by tryolivier** [IchorDev/Latch#32]
hello

Can the admin see what there are in a chest locked by a player ?

because I am /op but I have the sentence You cannot access this lock

thanks to add that admin with permission can open locked chest

thanks ;)

have a nice day

**Comment by parlough** [comment]
Sorry I never responded to this, I forgot to come back to it. The issue is likely that you need to use `/latch bypass` as it is what allows you to open other's locks.

If you are using a permissions plugin you will need the permission `latch.admin.bypass` which you automatically have if you have `latch.admin`.
