### ISSUE TITLE
can't lock doot in biomes o' plenty mod

### ISSUE THREAD

**Issue by RainSeaiZinc** [IchorDev/Latch#33]
input That is not a lockable block: tile.fir_door_block.name 
but me add the fir_door's item id:"biomesoplenty:fir_door" into config latch.conf
please fix it

**Comment by parlough** [comment]
I'm really sorry for the long wait, I don't remember seeing this. If this is still an issue for you or for someone else, I'm assuming the id you put is just wrong. It's like `biomesoplenty:fir_door_block`. I'm not able to test this, but it seems likely since they append `_block` on to `fir_door` here: https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.12.x-7.0.x/src/main/java/biomesoplenty/common/init/ModBlocks.java#L330

If there's any other issues, let me know.
