### ISSUE TITLE
Public locks with redstone protection issue

### ISSUE THREAD

**Issue by Big-Deaddy** [IchorDev/Latch#7]
The public locks don't seem to follow the same rules as private locks when it comes to the new redstone protection whitelist feature. I tried to use a public pressure plate to open a public fence gate, and the gate opened once but wouldn't close after stepping off the place. After that it wouldn't trigger at all.

Latch-0.3.1
spongeforge-1.10.2-2202-5.1.0-BETA-2093

**Comment by Big-Deaddy** [comment]
Update:
After some further testing, I noticed that pressure plates in general that have the problem with any lock type.

**Comment by parlough** [comment]
So I'm not able to test anything right now, but could you try not locking the pressure plates and seeing if the protection works as expected. We were not able to get pressure plates to distinguish based on their lock without many problems so that is why we added checks for who was the source of the redstone signal affecting the other locked blocks. So like if a door is marked private only people with access to it will be able to open it with a pressure plate. It's dependant on the other locked object, not the pressure plate.

**Comment by Big-Deaddy** [comment]
Unlocked pressure plates still don't work with any kind of locked object unless redstone protection is disabled.

**Comment by Big-Deaddy** [comment]
Apparently breaking and replacing both the pressure plate and locked blocks fixed it, must've been the most recent Sponge update.

**Comment by parlough** [comment]
Closing this for now. If the problem occurs again please reopen the issue. Thanks!
